# Edit this file to set the Messenger's module settings programmatically instead of using the GUI
# This is regular YAML syntax. See http://docs.ansible.com/ansible/YAMLSyntax.html
# You can override these settings with ENV variables. They are commented below.

hostname: "https://95d29608.ngrok.io/" # MESSENGER_HOST

applicationID: "815871605249936" # MESSENGER_APP_ID
accessToken: "EAALmBZBk2l5ABAPECal8LkWbTJofcYk6CZB04RlEjRAXizAo4j4gw8c744b5rEuItcuujZCoZBZAIKK9kGO7LLZApJeBz44gw91vgeMBd1P2rEmecZAzAgYbV7KmzhL4wocciZCbGjZAcKStfFF97jPnTuFGKLoZApg5lLrBfBCBBhdQZDZD" # MESSENGER_ACCESS_TOKEN
appSecret: "028199799be17d2fed2aa16e91de9d4c" # MESSENGER_APP_SECRET

verifyToken: "123456" # MESSENGER_VERIFY_TOKEN

displayGetStarted: true
greetingMessage: "Hello"

# https://developers.facebook.com/docs/messenger-platform/messenger-profile/persistent-menu
# persistentMenuItems: []

# targetAudience: openToAll
# targetAudienceOpenToSome: ""
# targetAudienceCloseToSome: ""

# trustedDomains: []
# autoRespondGetStarted: true

# paymentTesters: []

# chatExtensionHomeUrl: ""
# chatExtensionInTest: true
# chatExtensionShowShareButton: false

enabled: true